"""Simulated engine.

- Demo footage generated by `app.demo.generate` carries a ground-truth sidecar: tracks come straight from it,
  so boxes sit exactly on the drawn subjects.
- Any other file gets plausible, deterministic (seeded by the file hash) tracks so every screen can be exercised
  before a real model is plugged in. These are labelled "AI mô phỏng" in the UI.

Processing time follows the URD estimate (dur × fps × (0.04 + 0.015 × modes)) so progress and early alerts behave
like the real pipeline.
"""

import hashlib
import json
import random
import time

from ..domain import COLORS, mode_count
from .base import TrackResult, VideoInfo, apply_modes
from .features import identity_vector

PERSON_COLORS = ["black", "white", "gray", "blue", "red", "green", "yellow", "pink", "beige", "brown", "orange", "purple", "cyan"]
VEHICLE_COLORS = ["silver", "white", "black", "gray", "red", "blue", "yellow", "green"]
SERIES = "ABCDEFGHKLMNPSTVXZ"


def plate_alternatives(p: str) -> list[dict]:
    last = p[-1]
    a1 = p[:-1] + (str((int(last) + 3) % 10) if last.isdigit() else "0")
    a2 = (p[:2] + ("H" if p[2] == "A" else "C") + p[3:]) if len(p) > 2 and p[2].isalpha() else p
    return [{"text": a1, "confidence": 19}, {"text": a2, "confidence": 6}]


def _sample(boxes: list[dict], fps: float, t_in: float, t_out: float) -> list[dict]:
    if not boxes:
        return []
    step = 1.0 / max(fps, 0.01)
    out, nxt = [], t_in
    for b in boxes:
        if b["t"] + 1e-6 >= nxt:
            out.append(b)
            nxt = b["t"] + step
    if out[-1]["t"] < t_out - 1e-6 and boxes[-1] is not out[-1]:
        out.append(boxes[-1])
    return out


class SimulatedEngine:
    name = "simulated"

    def __init__(self, speed: float = 1.0, inject_plates: list[str] | None = None) -> None:
        self.speed = speed
        self.inject_plates = inject_plates or []

    # -- track sources ------------------------------------------------------------------------------
    def _from_truth(self, video: VideoInfo) -> list[TrackResult]:
        data = json.loads(video.truth.read_text(encoding="utf-8"))
        out = []
        for t in data["tracks"]:
            out.append(TrackResult(
                track_id=t["track_id"], kind=t["kind"], t_in=t["t_in"], t_out=t["t_out"], boxes=t["boxes"], confidence=t["confidence"],
                attributes=dict(t.get("attributes", {})), plate_text=t.get("plate"), plate_confidence=t.get("plate_confidence"),
                plate_alternatives=plate_alternatives(t["plate"]) if t.get("plate") else [], identity=t.get("identity"),
                face_box=t.get("face_box"), best_t=t.get("best_t"),
            ))
        return out

    def _synth(self, video: VideoInfo) -> list[TrackResult]:
        rng = random.Random(hashlib.sha256((video.seed or str(video.path)).encode()).hexdigest())
        dur = max(video.duration, 4.0)
        out: list[TrackResult] = []
        n_people = max(3, min(14, int(dur / 10)))
        n_cars = max(1, min(6, int(dur / 25)))

        def path(x0, y, w, h, vx, t_in, t_out):
            boxes, t = [], t_in
            while t <= t_out + 1e-6:
                x = min(max(x0 + (t - t_in) * vx, 0.0), 100 - w)
                boxes.append({"t": round(t, 2), "x": round(x, 2), "y": round(y, 2), "w": w, "h": h})
                t += 0.2
            return boxes

        for i in range(n_people):
            span = rng.uniform(min(6, dur * 0.5), max(6.5, min(40, dur * 0.6)))
            t_in = round(rng.uniform(0, max(0.1, dur - span)), 2)
            t_out = round(min(dur, t_in + span), 2)
            mask = rng.random() < 0.2
            attrs = {
                "gender": rng.choice("mf"), "top": rng.choice(["long", "short"]), "top_color": rng.choice(PERSON_COLORS),
                "bottom": rng.choice(["pants", "pants", "shorts", "skirt"]), "bottom_color": rng.choice(PERSON_COLORS),
                "mask": mask, "accessories": [a for a in ("bag", "hat") if rng.random() < 0.35], "gait": rng.choice(["normal", "fast", "slow"]),
            }
            if attrs["gender"] == "m" and attrs["bottom"] == "skirt":
                attrs["bottom"] = "pants"
            w, h = 5.5, 29.0
            x0, y = rng.uniform(5, 85), rng.uniform(35, 62)
            vx = rng.choice([-1, 1]) * rng.uniform(0.3, 1.2)
            boxes = path(x0, y, w, h, vx, t_in, t_out)
            mid = boxes[len(boxes) // 2]
            sig = f"{attrs['gender']}{attrs['top']}{attrs['top_color']}{attrs['bottom']}{attrs['bottom_color']}"
            out.append(TrackResult(
                track_id=f"P{i + 1:02d}", kind="person", t_in=t_in, t_out=t_out, boxes=boxes, confidence=round(rng.uniform(72, 98)),
                attributes=attrs, identity="sig:" + sig, best_t=mid["t"],
                face_box=None if mask else {"t": mid["t"], "x": mid["x"] + w * 0.2, "y": mid["y"], "w": w * 0.6, "h": h * 0.24},
            ))
        for i in range(n_cars):
            span = rng.uniform(min(6, dur * 0.4), max(6.5, min(30, dur * 0.5)))
            t_in = round(rng.uniform(0, max(0.1, dur - span)), 2)
            t_out = round(min(dur, t_in + span), 2)
            if i == 0 and self.inject_plates:
                plate = self.inject_plates[0]
            else:
                plate = f"{rng.randint(29, 99)}{rng.choice(SERIES)}-{rng.randint(100, 999)}.{rng.randint(0, 99):02d}"
            w = h = 22.0
            x0, y = rng.uniform(5, 70), rng.uniform(40, 55)
            vx = rng.choice([-1, 1]) * rng.uniform(0.15, 0.6)
            boxes = path(x0, y, w, h, vx, t_in, t_out)
            mid = boxes[len(boxes) // 2]
            out.append(TrackResult(
                track_id=f"X{i + 1:02d}", kind="vehicle", t_in=t_in, t_out=t_out, boxes=boxes, confidence=round(rng.uniform(80, 98)),
                attributes={"vehicle_type": rng.choice(["car", "car", "suv", "motorbike", "truck"]), "color": rng.choice(VEHICLE_COLORS)},
                plate_text=plate, plate_confidence=round(rng.uniform(55, 97)), plate_alternatives=plate_alternatives(plate), best_t=mid["t"],
            ))
        return out

    # -- run ----------------------------------------------------------------------------------------
    def analyze(self, video: VideoInfo, fps: float, modes: dict, on_progress, on_track) -> list[TrackResult]:
        raw = self._from_truth(video) if video.truth and video.truth.exists() else self._synth(video)
        for t in raw:
            if t.kind == "person" and t.face_box and t.identity:
                t.face_vector = identity_vector(t.identity, jitter=f"{video.seed}:{t.track_id}")
        tracks = []
        for t in raw:
            t = apply_modes(t, modes)
            if t is None:
                continue
            t.boxes = _sample(t.boxes, fps, t.t_in, t.t_out)
            tracks.append(t)
        tracks.sort(key=lambda t: t.t_in)

        dur = max(video.duration, 1.0)
        budget = dur * fps * (0.04 + 0.015 * mode_count(modes)) * self.speed
        batches = max(1, min(60, int(dur / 2)))
        emitted = set()
        for b in range(batches):
            t_end = dur * (b + 1) / batches
            if budget > 0:
                time.sleep(budget / batches)
            for t in tracks:
                # A track is "solid" one second after it appears (enough frames for OCR / a frontal face).
                if t.track_id not in emitted and min(t.t_in + 1.0, t.t_out) <= t_end:
                    emitted.add(t.track_id)
                    on_track(t)
            on_progress(min(99.0, 100.0 * (b + 1) / batches))
        for t in tracks:
            if t.track_id not in emitted:
                on_track(t)
        return tracks


def color_hex(key: str) -> str:
    return COLORS.get(key, COLORS["gray"])["hex"]
