/** Chain-of-custody action catalogue; mirrors backend/app/services/audit.py ACTIONS. */
const ACTIONS: Record<string, [string, string]> = {
  LOGIN_OK: ['Đăng nhập thành công', 'Signed in'],
  LOGIN_FAIL: ['Đăng nhập thất bại', 'Failed sign-in'],
  LOGIN_LOCKED: ['Tài khoản tạm khóa', 'Account locked'],
  LOGOUT: ['Đăng xuất', 'Signed out'],
  SESSION_LOCK: ['Khóa phiên', 'Locked session'],
  SESSION_UNLOCK: ['Mở khóa phiên', 'Unlocked session'],
  SESSION_PIN_FAIL: ['Nhập sai PIN', 'Wrong PIN'],
  CASE_OPEN: ['Mở hồ sơ vụ án', 'Opened case'],
  CASE_UPDATE: ['Cập nhật vụ án', 'Updated case'],
  EVIDENCE_INGEST: ['Nhập chứng cứ', 'Ingested evidence'],
  EVIDENCE_HASH: ['Tính mã băm SHA-256', 'Computed SHA-256'],
  EVIDENCE_REJECT: ['Lỗi toàn vẹn khi tiếp nhận', 'Integrity failure at intake'],
  EVIDENCE_VERIFY_OK: ['Xác minh SHA-256 khớp', 'SHA-256 verified'],
  EVIDENCE_VERIFY_FAIL: ['Phát hiện lệch mã băm', 'Hash mismatch detected'],
  ANALYSIS_QUEUE: ['Đưa vào hàng đợi phân tích', 'Queued for analysis'],
  ANALYSIS_DONE: ['Hoàn tất phân tích AI', 'AI analysis complete'],
  ANALYSIS_FAIL: ['Phân tích AI lỗi', 'AI analysis failed'],
  ANALYSIS_REQUEUE: ['Yêu cầu phân tích lại', 'Requested re-analysis'],
  EVIDENCE_REMOVE: ['Gỡ chứng cứ khỏi vụ án', 'Removed evidence from case'],
  VIDEO_RENAME: ['Đổi tên hiển thị video', 'Renamed video'],
  CLIP_CREATE: ['Cắt đoạn video', 'Cut clip'],
  SNAPSHOT: ['Chụp khung hình', 'Captured frame'],
  BOOKMARK: ['Đánh dấu thời điểm', 'Bookmarked moment'],
  TAG_SUBJECT: ['Gắn thẻ đối tượng', 'Tagged subject'],
  TAG_DELETE: ['Xóa thẻ', 'Deleted tag'],
  IMAGE_EXPORT: ['Xuất ảnh', 'Exported image'],
  IMAGE_TO_REPORT: ['Chèn ảnh vào báo cáo', 'Inserted image into report'],
  VIDEO_ENHANCE: ['Xuất video đã cải thiện', 'Exported enhanced video'],
  REPORT_PDF: ['Tạo báo cáo PDF', 'Generated PDF report'],
  PACKAGE_EXPORT: ['Xuất gói chứng cứ', 'Exported evidence package'],
  PACKAGE_BLOCKED: ['Chặn xuất gói do lệch mã băm', 'Package blocked by hash mismatch'],
  ZONE_CREATE: ['Tạo vùng nhận diện', 'Created zone'],
  ZONE_DELETE: ['Xóa vùng nhận diện', 'Deleted zone'],
  WATCH_ADD: ['Thêm vào danh sách theo dõi', 'Added to watchlist'],
  WATCH_REMOVE: ['Xóa khỏi danh sách theo dõi', 'Removed from watchlist'],
  WATCH_ALERT: ['Cảnh báo danh sách theo dõi', 'Watchlist alert'],
  SEARCH_FACE: ['Tìm theo ảnh khuôn mặt', 'Face photo search'],
  SEARCH_PLATE: ['Tìm theo biển số', 'Plate search'],
  CAMERA_ADD: ['Thêm camera', 'Added camera'],
  CAMERA_ASSIGN: ['Gán vị trí camera cho chứng cứ', 'Assigned camera location'],
  CAMERA_MOVE: ['Chỉnh vị trí camera', 'Moved camera'],
  SETTINGS_CHANGE: ['Đổi cài đặt phân tích', 'Changed analysis settings'],
  AI_QUESTION: ['Hỏi trợ lý AI', 'Asked AI assistant'],
  USER_ADMIN: ['Quản trị người dùng', 'User administration'],
  AUDIT_CHAIN_OK: ['Kiểm tra chuỗi nhật ký: hợp lệ', 'Audit chain verified'],
  AUDIT_CHAIN_BROKEN: ['Kiểm tra chuỗi nhật ký: bị sửa đổi', 'Audit chain broken'],
}

export const auditLabel = (code: string, lang: 'vi' | 'en') => (ACTIONS[code] ? ACTIONS[code][lang === 'vi' ? 0 : 1] : code)
